apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kbs-route
  namespace: trustee-operator-system
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  port:
    targetPort: kbs-port
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kbs-service
